name: "Testing Backend"
on: ["push"]

jobs:
  Testing:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Setup Nodejs"
        uses: actions/setup-node@v3.4.1
        with:
          node-version: "18.x"
          persist-credentials: false
      - name: "Install dependencies"
        run: |
          npm install
      - name: "Run tests"
        run: |
          npm test
