name: Node.js CI

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 18.x
      - name: Install dependencies
        run: |
          npm install
      - name: Test
        run: |
          npm test    
